# Generated by Django 6.0.3 on 2026-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
