# Generated by Django 6.0.3 on 2026-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cv_url_user_education_level_user_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv_url',
        ),
        migrations.AddField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='instructor_cvs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proposed_courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
