# Generated by Django 6.0.3 on 2026-03-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
