# Generated by Django 6.0.3 on 2026-04-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_migrate_user_data_to_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved_instructor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proposed_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_of_experience',
        ),
    ]
