# Generated by Django 6.0.3 on 2026-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_bio_remove_user_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_type',
            field=models.CharField(choices=[('VIDEO_CREATOR', 'Video Creator'), ('LIVE_STREAMER', 'Live Streamer'), ('BOTH', 'Both')], default='VIDEO_CREATOR', max_length=20),
        ),
    ]
