# Generated by Django 6.0.3 on 2026-03-29 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0013_remove_courseview_course_remove_courseview_user_and_more'),
        ('finance', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_artifact', to='interactions.enrollment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_flow', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'balance'], name='finance_wal_user_id_cba405_idx'),
        ),
    ]
