# Generated by Django 6.0.3 on 2026-04-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('finance', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreampayment',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_artifact', to='interactions.livestreamenrollment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_artifact', to='interactions.enrollment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
