# Generated by Django 6.0.3 on 2026-04-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorreview',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorreview',
            name='live_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_reviews', to='courses.livestream'),
        ),
        migrations.AddField(
            model_name='instructorreview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_instructor_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mastery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestreamenrollment',
            name='live_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.livestream'),
        ),
        migrations.AddField(
            model_name='livestreamenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestream_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_reviews', to='courses.course'),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='instructorreview',
            unique_together={('instructor', 'student', 'live_stream')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='livestreamenrollment',
            unique_together={('student', 'live_stream')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('course', 'student')},
        ),
    ]
