# Generated by Django 6.0.3 on 2026-03-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_views_count_alter_category_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
