# Generated by Django 6.0.3 on 2026-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_blocks/images/'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='content_blocks/pdfs/'),
        ),
    ]
