# Generated by Django 6.0.3 on 2026-03-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_contentblock_image_contentblock_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='content_blocks/videos/'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
