# Generated by Django 6.0.3 on 2026-03-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_courseview_course_remove_courseview_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('LIVE_TUTORIAL', 'Live Tutorial Hub'), ('HARD_SKILL_RECORDED', 'Hard Skill (Pre-recorded Adaptive)'), ('SOFT_SKILL', 'Soft Skill Mastery')], db_index=True, default='HARD_SKILL_RECORDED', max_length=30),
        ),
    ]
