# Generated by Django 6.0.3 on 2026-04-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_category_created_at_alter_chapter_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
