# Generated by Django 6.0.3 on 2026-04-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_has_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='live_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='meeting_link',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('VIDEO_BASED', 'Video-Based Course'), ('LIVE_STREAM', 'Live Stream Course')], db_index=True, default='VIDEO_BASED', max_length=30),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='group_type',
            field=models.CharField(choices=[('VVIP', 'VVIP (1 Student)'), ('VIP1', 'VIP1 (5 Students)'), ('VIP2', 'VIP2 (10 Students)'), ('NORMAL', 'Normal (100 Students)')], default='VIP1', max_length=10),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.livestream')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='live_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.livesession'),
        ),
    ]
